### ISSUE TITLE
abstract/sec/title:

### ISSUE THREAD

**Issue by jorgesallum** [scielo-edo/SPS-TeX#39]
http://jats2tex.beijaflor.io/workspaces/13

Da maneira como está definida no exemplo do link acima, perdemos a informação do abstract/sec/title

Pensei em definir assim, mas infelizmente a definição de um nódulo abaixo neutraliza os de cima: 

`abstract/sec/title: "\\section{@@children}`. 

Tentei definir dentro do ambiente, mas não consegui concatenar com os parágrafos. 

```
abstract: 

  head:  |
  
    \ifdef{\abstracttitle}{\renewcommand{\abstractname}{\abstracttitle}{}
    
  body: |
  
    \begin{abstract}
    @@lua(return "\\newcommand{\\abstracttitle}{" .. find('abstract/title') .. "}")@@
    @@lua(return "\\section{" .. find('//sec/title') .. "}")@@
    @@lua(return find "//p")@@
    \ifdef{\kwdgroup}{\kwdgroup}{}
    \end{abstract}
```

**Comment by yamadapc** [comment]
Como precisa ser a saída?

**Comment by yamadapc** [comment]
Ping
